issues 64 翻译完成
SwiftGGTeam/apple-dev-doc-translation pull request #105
Opened 2023-12-09 08:14 UTC by Airwen

2023-12-18 01:23 UTC, hiETsang requested changes
内容很 ok，还加了很多提示👍
还需要注意一下标点符号和空格，需要再检查一下

2023-12-18 01:23 UTC, hiETsang commented on project/visionos/understanding-the-realitykit-modular-architecture.yml
> +  翻译: '理解在RealityKit中一切如何相互配合'
这里中英文空格

2023-12-18 01:23 UTC, hiETsang commented on project/visionos/understanding-the-realitykit-modular-architecture.yml
> +  翻译: 'RealityKit 是专为构建应用程序、游戏和其他沉浸式体验而设计的 3D 框架。虽然，它是使用面向对象的编程语言和设计原则，但是 RealityKit 采用了“实体-组件-系统”架构范式，将应用程序中对象分为 “实体 Entity ”，“组件 Component ”，”系统 System “三种，从而避免“组合模式”的繁重设计——通过添加实例变量来持有其他对象引用从而构建对象。
采用了“实体-组件-系统”架构范式    空格需要注意一下，改为  采用了 “实体-组件-系统” 架构范式

2023-12-18 01:23 UTC, hiETsang commented on project/visionos/understanding-the-realitykit-modular-architecture.yml
> +  翻译: '系统包含 实现特定类型实体的行为，或者 更新特殊类型实体的状态 的代码，而 RealityKit 会在每帧调用“系统”的代码。系统使用组件存储实体特定状态，同时可以通过 某种类型组件 或者 多种类型组件组合 查询需要进行操作的实体。'
这里的文字之间空格可以去掉

2023-12-18 01:23 UTC, hiETsang commented on project/visionos/understanding-the-realitykit-modular-architecture.yml
> +  翻译: '例如，游戏可以通过 伤害系统 监听和更新实体生命值，这样实体就可以被伤害或者被毁灭。系统会通常操作一个或多个组件，所以伤害系统通过生命值组件 记录每个实体受到的伤害值，以及每个实体在被毁灭之前还能承受多少伤害。系统也会和其他的组件交互。比如，实体也可以有保护作用的盔甲组件，这时伤害系统也会去使用该组件存储的状态值。'
空格需要调整下

2024-01-29 10:54 UTC, JacobMao approved these changes

2024-01-31 02:16 UTC, JacobMao commented
@hiETsang can you review this PR again? thanks

2024-02-01 01:25 UTC, hiETsang approved these changes

2024-02-01 01:26 UTC, merged